# Generated by Django 3.1.8 on 2021-04-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='song',
            name='poster',
            field=models.ImageField(upload_to='image'),
        ),
    ]
