# Generated by Django 3.1.8 on 2021-04-19 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20210414_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music',
            field=models.FileField(upload_to='audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
