# Generated by Django 3.1.8 on 2021-04-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_mostwatch_relatedsimilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostwatch',
            name='mostwatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mostwatchs', to='music_app.video'),
        ),
        migrations.AlterField(
            model_name='relatedsimilar',
            name='relatedsimilar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedsimilars', to='music_app.video'),
        ),
    ]
